### ISSUE TITLE
Can't access wallet option menu for wallets at the bottom of the screen.

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#790] opened 2022-02-17 15:20 UTC
On the wallet page if there are enough wallets to fill the screen, the options for the wallet at the bottom of the screen is not fully shown. Tested on a computer running linux.

![godcr-wallet-page](https://user-images.githubusercontent.com/4796738/154512206-20356019-77d1-45b1-9240-5dfc6bfce4db.png)

**Comment by Sirmorrison** [comment] 2022-02-17 19:22
Duplicate of #727 hence closing it as it is currently being worked on by Ebuka

**Closed as completed by Sirmorrison** 2022-02-17 19:22 UTC
