### ISSUE TITLE
Send page wallet and acount tab reshuffle.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#138] opened 2020-06-07 09:49 UTC
### Describe the bug
*A clear and concise description of what the bug is.*
On the send page, when a new wallet or account is selected, the wallets reshuffles. This happens only on the send page.
Also the pages flicks showing `LOADING` in the background before rendering the send page.

### To Reproduce
 - *On page send page,*
 - *When I click on a wallet or on an account under a selected wallet, the wallets tab reshuffles the wallet position.*

### Expected behavior
*A clear and concise description of what you expected to happen.*
Kindly observe other pages, when a wallet is selected or an account is selected, the wallets on the wallet tabs retain their position.

### Relevant screenshots or logs
*If applicable, add screenshots or log entries to help explain your problem.*

![ezgif com-video-to-gif(8)](https://user-images.githubusercontent.com/27733432/83965613-bc95da00-a8ac-11ea-8fb7-3fb798ddfd80.gif)

**Comment by oshorefueled** [comment] 2020-06-07 14:37
duplicate of #121

**Closed as completed by oshorefueled** 2020-06-07 14:37 UTC
Labels: bug
