### ISSUE TITLE
having only watch only wallets, the wallet menu is hidden

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#949] opened 2022-05-24 16:21 UTC
having only watch only wallets, the wallet menu is hidden

<img width="797" alt="image" src="https://user-images.githubusercontent.com/27733432/170084601-9e1b7922-eaf8-40d5-810d-9013221920d1.png">

**Comment by dreacot** [comment] 2022-05-26 22:38
duplicate of https://github.com/planetdecred/godcr/issues/940

**Closed as completed by dreacot** 2022-05-26 22:38 UTC
