### ISSUE TITLE
proposals: Crash on tab navigation.

### ISSUE THREAD

**Issue by victorgcramos** [planetdecred/godcr#683] opened 2021-11-06 03:38 UTC
App crashes when navigating from **Approved** -> **In Discussion**

![godcr-proposals](https://user-images.githubusercontent.com/22639213/140596654-dae18d5c-d715-4908-b917-ed380b22a337.gif)

**Comment by Sirmorrison** [comment] 2021-11-06 08:15
The proposals section will be undergoing major UI updates.   Any bugs will be resolved with the update

**Comment by victorgcramos** [comment] 2021-11-06 13:52
@Sirmorrison oh, sure! Thanks 😊

**Comment by devchoplife** [comment] 2021-11-06 18:14
I cannot reproduce it though, did you build the current master @victorgcramos ?

**Comment by victorgcramos** [comment] 2021-11-12 23:41
@devchoplife yes, I'm running master. Maybe my wallet syncing status had something to do with it.

**Closed as completed** 2021-11-19 20:09 UTC

**Comment by victorgcramos** [comment] 2021-11-20 14:29
Thank you guys! 🦬🦬
