### ISSUE TITLE
Cannot access watch-only wallet options menu

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#961] opened 2022-05-31 08:35 UTC
After pulling the current master I cannot access watch-only wallets option menu. See video below.

https://user-images.githubusercontent.com/4796738/171129895-77b93976-7164-48c5-9552-8fc2b4d7eedc.mp4

**Comment by Sirmorrison** [comment] 2022-05-31 08:48
Duplicate of #940

**Comment by crux25** [comment] 2022-05-31 09:03
This is not a duplicate of #940. 

For #940:
- Watch only wallet need to be the only wallet on the list.
- The menu is hidden just above the send/receive navigation area.
- It existed on master before May 27, 2022.

For #961:
- Instead of showing options menu it takes you to wallet details page.
- If you roll back the master head to commits before May 27 this bug disappears.

**Closed as completed** 2022-06-07 23:36 UTC

**Comment by Sirmorrison** [comment] 2022-06-16 06:15
This is resolved.
