### ISSUE TITLE
Wallet list order is changed when click on tab in Send page

### ISSUE THREAD

**Issue by skynet0590** [planetdecred/godcr#140] opened 2020-06-07 10:35 UTC
### Describe the bug
Wallet list order is changed when click on tab in Send page

### To Reproduce
 - *On page *: `Send`
 - When I click on wallet of list wallet on the top. The wallet information will change into there wallet. It is right but the list will be changed and it is not correct anymore

### Expected behavior
The list should not changed 

### Platform

[- ] Linux

[ ] MacOS

[ ] Windows

### Relevant screenshots or logs
![Screenshot from 2020-06-07 17-28-24](https://user-images.githubusercontent.com/54076217/83966576-2f22ac00-a8e5-11ea-846a-b8986f1c0133.png)
![Screenshot from 2020-06-07 17-29-00](https://user-images.githubusercontent.com/54076217/83966578-321d9c80-a8e5-11ea-8a1d-06eb3d6c7253.png)

**Comment by oshorefueled** [comment] 2020-06-07 14:38
duplicate of #121

**Closed as completed by oshorefueled** 2020-06-07 14:38 UTC
Labels: bug
